# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Simple"
license = "MIT"
licenselink = "https://github.com/bodani/Simple/blob/master/LICENSE.md"
description = "An elegant open-source and mobile-first theme"
homepage = "http://example.com/"
tags = ["blog", "company"]
features = ["blog"]
min_version = 0.24

[author]
    name = "Eamon"
    homepage = "https://github.com/bodani/Simple/"

